### ISSUE TITLE
NullPointerException on startup caused by Twilight Forest

### ISSUE THREAD

**Issue by Endoman123** [Wehavecookies56/Kingdom-Keys-Re-Coded#48]
FML crashes when KK Re:Coded starts up in my modpack. I tested KK by itself and it starts up fine, so there must be a conflict somewhere. Unfortunately, the stacktrace/crash report gives no indication of where the conflict might be with my other mods.

## Game Info
Minecraft Version: 1.12
FML Version: 14.23.3.2697

## Crash Report
<details>
<summary>Click Here</summary>

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Kingdom Keys Re:Coded (kk)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.common.registry.EntityRegistry.addSpawn(EntityRegistry.java:239)
	at uk.co.wehavecookies56.kk.common.core.proxy.CommonProxy.init(CommonProxy.java:171)
	at uk.co.wehavecookies56.kk.client.core.proxy.ClientProxy.init(ClientProxy.java:935)
	at uk.co.wehavecookies56.kk.common.KingdomKeys.init(KingdomKeys.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1198339472 bytes (1142 MB) / 3361374208 bytes (3205 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 5 total; -XX:+UseConcMarkSweepGC -XX:ParallelCMSThreads=2 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2697 Optifine OptiFine_1.12.2_HD_U_D3 91 mods loaded, 91 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version           | Source                                            | Signature                                |
	|:----- |:-------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                  | 1.12.2            | minecraft.jar                                     | None                                     |
	| UCHI  | mcp                        | 9.42              | minecraft.jar                                     | None                                     |
	| UCHI  | FML                        | 8.0.99.99         | forge-1.12.2-14.23.3.2697-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                      | 14.23.3.2697      | forge-1.12.2-14.23.3.2697-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | advancedrocketrycore       | 1                 | minecraft.jar                                     | None                                     |
	| UCHI  | opencomputers|core         | 1.7.2.67          | minecraft.jar                                     | None                                     |
	| UCHI  | redstoneflux               | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal.jar           | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHI  | cofhcore                   | 4.4.1             | CoFHCore-1.12.2-4.4.1.12-universal.jar            | None                                     |
	| UCHI  | libvulpes                  | 0.2.8.-31         | LibVulpes-1.12.2-0.2.8-31-universal.jar           | None                                     |
	| UCHI  | advancedrocketry           | 1.4.0.-80         | AdvancedRocketry-1.12.2-1.4.0-80.jar              | None                                     |
	| UCHI  | infinitylib                | 1.12.2-1.12.0     | infinitylib-1.12.0.jar                            | None                                     |
	| UCHI  | agricraft                  | 2.12.0-1.12.0-a4  | agricraft-2.12.0-1.12.0-a4.jar                    | None                                     |
	| UCHI  | jei                        | 4.9.1.187         | jei_1.12.2-4.9.1.187.jar                          | None                                     |
	| UCHI  | appleskin                  | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| UCHI  | appliedenergistics2        | rv5-stable-11     | appliedenergistics2-rv5-stable-11.jar             | None                                     |
	| UCHI  | aquaculture                | 1.6.2             | Aquaculture-1.12.2-1.6.2.jar                      | None                                     |
	| UCHI  | aroma1997core              | 1.3.0.2           | Aroma1997Core-1.12.2-1.3.0.2.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHI  | aroma1997sdimension        | 1.3.0.0.b37       | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UCHI  | morphtool                  | 1.2-16            | Morph-o-Tool-1.2-16.jar                           | None                                     |
	| UCHI  | autoreglib                 | 1.3-17            | AutoRegLib-1.3-17.jar                             | None                                     |
	| UCHI  | codechickenlib             | 3.1.8.341         | CodeChickenLib-1.12.2-3.1.8.341-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI  | avaritia                   | 3.2.0             | Avaritia-1.12-3.2.0.13-universal.jar              | None                                     |
	| UCHI  | badwithernocookiereloaded  | 1.12.1-2.12       | badwithernocookiereloaded-1.12.1-2.12.jar         | None                                     |
	| UCHI  | baubles                    | 1.5.2             | Baubles-1.12-1.5.2.jar                            | None                                     |
	| UCHI  | bdlib                      | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| UCHI  | biomesoplenty              | 7.0.1.2384        | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar     | None                                     |
	| UCHI  | cofhworld                  | 1.1.1             | CoFHWorld-1.12.2-1.1.1.12-universal.jar           | None                                     |
	| UCHI  | compactmachines3           | 3.0.11            | compactmachines3-1.12.2-3.0.11-b207.jar           | None                                     |
	| UCHI  | controlling                | 3.0.6             | Controlling-3.0.6.jar                             | None                                     |
	| UCHI  | ctm                        | MC1.12-0.2.3.12   | CTM-MC1.12-0.2.3.12.jar                           | None                                     |
	| UCHI  | cucumber                   | 1.1.0             | cucumber-1.12-1.1.0.jar                           | None                                     |
	| UCHI  | custommainmenu             | 2.0.8             | CustomMainMenu-MC1.12.2-2.0.8.jar                 | None                                     |
	| UCHI  | orespawn                   | 3.3.0             | OreSpawn-1.12-3.3.0.136.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | densemetals                | 1.2.0             | DenseMetals-1.12-1.2.0.20.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHI  | endercore                  | 1.12.2-0.5.22     | EnderCore-1.12.2-0.5.22.jar                       | None                                     |
	| UCHI  | thermalfoundation          | 2.4.1             | ThermalFoundation-1.12.2-2.4.1.15-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI  | thermalexpansion           | 5.4.2             | ThermalExpansion-1.12.2-5.4.2.27-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHI  | enderio                    | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | enderiointegrationtic      | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | enderiobase                | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | enderioconduits            | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | forestry                   | 5.8.0.290         | forestry_1.12.2-5.8.0.290.jar                     | None                                     |
	| UCHI  | enderiointegrationforestry | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | enderiointegrationticlate  | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | enderiomachines            | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | enderiopowertools          | 5.0.24            | EnderIO-1.12.2-5.0.24.jar                         | None                                     |
	| UCHI  | valkyrielib                | 1.12.2-2.0.10b    | valkyrielib-1.12.2-2.0.10b.jar                    | None                                     |
	| UCHI  | environmentaltech          | 1.12.2-2.0.10a    | environmentaltech-1.12.2-2.0.10a.jar              | None                                     |
	| UCHI  | opencomputers              | 1.7.2.67          | OpenComputers-MC1.12.2-1.7.2.67.jar               | None                                     |
	| UCHI  | zerocore                   | 1.12-0.1.2.1      | zerocore-1.12-0.1.2.1.jar                         | None                                     |
	| UCHI  | bigreactors                | 1.12.2-0.4.5.48   | ExtremeReactors-1.12.2-0.4.5.48.jar               | None                                     |
	| UCHI  | mekanism                   | 1.12.2-9.4.10.345 | Mekanism-1.12.2-9.4.10.345.jar                    | None                                     |
	| UCHI  | sonarcore                  | 5.0.9             | sonarcore-1.12.2-5.0.9.jar                        | None                                     |
	| UCHI  | fluxnetworks               | 3.0.8             | fluxnetworks-1.12.2-3.0.8.jar                     | None                                     |
	| UCHI  | forgemultipartcbe          | 2.4.2.58          | ForgeMultipart-1.12.2-2.4.2.58-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHI  | microblockcbe              | 2.4.2.58          | ForgeMultipart-1.12.2-2.4.2.58-universal.jar      | None                                     |
	| UCHI  | minecraftmultipartcbe      | 2.4.2.58          | ForgeMultipart-1.12.2-2.4.2.58-universal.jar      | None                                     |
	| UCHI  | gendustry                  | 1.6.5.8           | gendustry-1.6.5.8-mc1.12.2.jar                    | None                                     |
	| UCHI  | guideapi                   | 1.12-2.1.5-60     | Guide-API-1.12-2.1.5-60.jar                       | None                                     |
	| UCHI  | hammercore                 | 1.9.9.6           | HammerCore-1.12.2-1.9.9.6.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHI  | waila                      | 1.8.24            | Hwyla-1.8.24-B39_1.12.jar                         | None                                     |
	| UCHI  | jeibees                    | 0.9.0.5           | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
	| UCHI  | journeymap                 | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHI  | jeresources                | 0.8.7.41          | JustEnoughResources-1.12.2-0.8.7.41.jar           | None                                     |
	| UCHEE | kk                         | 1.0.0             | Kingdom+Keys+Re+Coded-1.12.2-1.0.0-68be54a.jar    | None                                     |
	| UCH   | lostcities                 | 2.0.7             | lostcities-1.12-2.0.7.jar                         | None                                     |
	| UCH   | radixcore                  | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar              | None                                     |
	| UCH   | mca                        | 1.12.2-5.3.1      | MCA-1.12.x-5.3.1-universal.jar                    | None                                     |
	| UCH   | mcjtylib_ng                | 2.6.7             | mcjtylib-1.12-2.6.7.jar                           | None                                     |
	| UCH   | mekanismgenerators         | 9.4.10            | MekanismGenerators-1.12.2-9.4.10.345.jar          | None                                     |
	| UCH   | mekanismtools              | 9.4.10            | MekanismTools-1.12.2-9.4.10.345.jar               | None                                     |
	| UCH   | morebees                   | 1.12.2-1.4.4      | morebees-1.12.2-1.4.4.jar                         | None                                     |
	| UCH   | mrtjpcore                  | 2.1.1.27          | MrTJPCore-1.12.2-2.1.1.27-universal.jar           | None                                     |
	| UCH   | projectred-core            | 4.8.6.74          | ProjectRed-1.12.2-4.8.6.74-Base.jar               | None                                     |
	| UCH   | projectred-integration     | 4.8.6.74          | ProjectRed-1.12.2-4.8.6.74-integration.jar        | None                                     |
	| UCH   | projectred-transmission    | 4.8.6.74          | ProjectRed-1.12.2-4.8.6.74-integration.jar        | None                                     |
	| UCH   | projectred-fabrication     | 4.8.6.74          | ProjectRed-1.12.2-4.8.6.74-fabrication.jar        | None                                     |
	| UCH   | rangedpumps                | 0.5               | rangedpumps-0.5.jar                               | None                                     |
	| UCH   | redstonearsenal            | 2.4.2             | RedstoneArsenal-1.12.2-2.4.2.9-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | resourceloader             | 1.5.3             | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCH   | rftools                    | 7.33              | rftools-1.12-7.33.jar                             | None                                     |
	| UCH   | roguelike                  | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| UCH   | simplyjetpacks             | 2.2.4.34          | SimplyJetpacks2-1.12.2-2.2.4.34.jar               | None                                     |
	| UCH   | solarfluxreborn            | 3.50r             | SolarFluxReborn_1.12.2-3.50r.jar                  | None                                     |
	| UCH   | thermalcultivation         | 0.2.0             | ThermalCultivation-1.12.2-0.2.0.6-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermaldynamics            | 2.4.1             | ThermalDynamics-1.12.2-2.4.1.10-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | thermalinnovation          | 0.2.1             | ThermalInnovation-1.12.2-0.2.1.6-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | twilightforest             | 3.7.424           | twilightforest-1.12.2-3.7.424-universal.jar       | None                                     |
	| UCH   | universalmodifiers         | 1.12.2-1.0.9a     | valkyrielib-1.12.2-2.0.10b.jar                    | None                                     |
	| UCH   | woot                       | 1.12.2-1.2.1      | woot-1.12.2-1.2.1.jar                             | None                                     |
	| UCH   | immersiveengineering       | 0.12-82           | ImmersiveEngineering-0.12-82.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-80.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.9.6.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.22.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
```
</details>

**Comment by EthanGold60** [comment]
Have you tried the trial and error approach yet? Sometimes it takes a while depending on the number of mods are in your modpack, but sometimes it's the best solution when you can't find the error in the crash report.

**Comment by Endoman123** [comment]
@EthanGold60 I was hoping that there would be a smarter way than just "brute forcing" the issue; e.g.: are there any mods in the mod list that you recognize have conflicts with EnderIO?

**Comment by Endoman123** [comment]
Update: Apparently the conflict is with The Twilight Forest; should I create a new issue or is it something that isn't going to be looked at?

**Comment by Wehavecookies56** [comment]
Oh interesting, I'll look into why that's causing that then, don't worry about creating a new issue
