### ISSUE TITLE
KK, CustomNPC, and Decocraft Crash Report

### ISSUE THREAD

**Issue by galhac** [Wehavecookies56/Kingdom-Keys-Re-Coded#49]
I've tried singling out which one it is but they only seem to crash when all three are together. Can anyone tell me why?

 ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/27/18 11:52 AM
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:239)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:230)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42)
	at net.minecraft.client.gui.GuiMainMenu.func_73970_b(GuiMainMenu.java:387)
	at net.minecraft.client.gui.GuiMainMenu.func_73971_c(GuiMainMenu.java:450)
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:478)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:239)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:230)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:198)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/gui/title/background/panorama_0.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42)
	at net.minecraft.client.gui.GuiMainMenu.func_73970_b(GuiMainMenu.java:387)
	at net.minecraft.client.gui.GuiMainMenu.func_73971_c(GuiMainMenu.java:450)
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:478)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (415, 44). Absolute: (830, 390)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 107530720 bytes (102 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(21jul17).jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJA	kk{0.9.0} [Kingdom Keys Re:Coded] (Kingdom+Keys+Re+Coded-1.10.2-0.9.0-25-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4815' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2511
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 22.20.16.4815, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Kingdom hearts style
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by Wehavecookies56** [comment]
That error is caused by Java running out of memory, allocate more.
